// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLQO0aAN2xt54JwSTsd-FdsqZPvgU5FkI',
    appId: '1:980899956979:web:c7dd24167ea23be4874f86',
    messagingSenderId: '980899956979',
    projectId: 'tap-to-rent',
    authDomain: 'tap-to-rent.firebaseapp.com',
    storageBucket: 'tap-to-rent.firebasestorage.app',
    measurementId: 'G-RMXN805ZPQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABBHRfgmdHcf--3dBBiJQJH5WEnYYd6g0',
    appId: '1:980899956979:ios:8a60a89c8377eebb874f86',
    messagingSenderId: '980899956979',
    projectId: 'tap-to-rent',
    storageBucket: 'tap-to-rent.firebasestorage.app',
    iosBundleId: 'com.example.tapToRent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLQO0aAN2xt54JwSTsd-FdsqZPvgU5FkI',
    appId: '1:980899956979:web:ba2359be50ec73d2874f86',
    messagingSenderId: '980899956979',
    projectId: 'tap-to-rent',
    authDomain: 'tap-to-rent.firebaseapp.com',
    storageBucket: 'tap-to-rent.firebasestorage.app',
    measurementId: 'G-L60413DCYX',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDLQO0aAN2xt54JwSTsd-FdsqZPvgU5FkI',
    appId: '1:980899956979:web:c7dd24167ea23be4874f86',
    messagingSenderId: '980899956979',
    projectId: 'tap-to-rent',
    authDomain: 'tap-to-rent.firebaseapp.com',
    storageBucket: 'tap-to-rent.firebasestorage.app',
    measurementId: 'G-RMXN805ZPQ',
  );
}
